name: Android CI

on:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android SDK components
        uses: android-actions/setup-android@v3
        with:
          components: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0
            ndk;27.1.12297006
            cmake;3.22.1

      - name: Set up Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build modules
        run: ./gradlew :app:assembleDebug :library:assembleRelease --stacktrace
