name: Android CI

on:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install PlantUML dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y plantuml graphviz

      - name: Install Android SDK components
        uses: android-actions/setup-android@v3
        with:
          components: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0
            ndk;27.1.12297006
            cmake;3.22.1

      - name: Set up Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build modules
        run: ./gradlew :app:assembleDebug :library:assembleRelease --stacktrace

      - name: Render PlantUML diagrams
        run: bash tools/render_docs.sh

      - name: Upload diagram artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs-diagrams
          path: docs/generated
