name: Build and Publish APK

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Install Android SDK components
        uses: android-actions/setup-android@v3
        with:
          components: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0
            ndk;27.1.12297006
            cmake;3.22.1

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Assemble release APK
        run: ./gradlew :app:assembleRelease --stacktrace

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/*.apk

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download release APK
        uses: actions/download-artifact@v4
        with:
          name: app-release-apk
          path: release-apk

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ github.run_number }}
          name: Build ${{ github.run_number }}
          generate_release_notes: true
          files: release-apk/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
